version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db_app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis_app
    ports:
      - "6400:6379"
    volumes:
      - redis-data:/data

  redis_for_test:
    image: redis:latest
    container_name: test_redis_app
    ports:
      - "6401:6379"
    volumes:
      - test-redis-data:/data

  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

  tests:
    build:
      context: .
    command: pytest -vv tests/
    depends_on:
      db:
        condition: service_healthy
      redis_for_test:
        condition: service_started

volumes:
  pgdata:
  redis-data:
  test-redis-data:
