version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db_app
    env_file:
      - .env-non-dev
    ports:
      - "5050:5432"

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db

  test: 
    build: 
      context: .
    command: pytest test/