version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db_app
    environment:
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - menu:/var/lib/postgresql/data/

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    ports:
      - "9000:8000"
    depends_on:
      - db

  tests:
    build:
      context: .
    command: pytest -vv tests/
    env_file:
      - .env-non-dev
    depends_on:
      - db

volumes:
  menu:
